// Generated by gencpp from file novatel_msgs/CommonFooter.msg
// DO NOT EDIT!


#ifndef NOVATEL_MSGS_MESSAGE_COMMONFOOTER_H
#define NOVATEL_MSGS_MESSAGE_COMMONFOOTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace novatel_msgs
{
template <class ContainerAllocator>
struct CommonFooter_
{
  typedef CommonFooter_<ContainerAllocator> Type;

  CommonFooter_()
    : checksum(0)  {
    }
  CommonFooter_(const ContainerAllocator& _alloc)
    : checksum(0)  {
  (void)_alloc;
    }



   typedef uint32_t _checksum_type;
  _checksum_type checksum;




  typedef boost::shared_ptr< ::novatel_msgs::CommonFooter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::novatel_msgs::CommonFooter_<ContainerAllocator> const> ConstPtr;

}; // struct CommonFooter_

typedef ::novatel_msgs::CommonFooter_<std::allocator<void> > CommonFooter;

typedef boost::shared_ptr< ::novatel_msgs::CommonFooter > CommonFooterPtr;
typedef boost::shared_ptr< ::novatel_msgs::CommonFooter const> CommonFooterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::novatel_msgs::CommonFooter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::novatel_msgs::CommonFooter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace novatel_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/jade/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/jade/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'novatel_msgs': ['/home/husai/16_novatel_span_driver/src/novatel_span_driver-serial_connection/novatel_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::novatel_msgs::CommonFooter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::novatel_msgs::CommonFooter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::novatel_msgs::CommonFooter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a3857d7abd4ce1de381cc063c02bc83";
  }

  static const char* value(const ::novatel_msgs::CommonFooter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a3857d7abd4ce1dULL;
  static const uint64_t static_value2 = 0xe381cc063c02bc83ULL;
};

template<class ContainerAllocator>
struct DataType< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "novatel_msgs/CommonFooter";
  }

  static const char* value(const ::novatel_msgs::CommonFooter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 checksum\n\
\n\
";
  }

  static const char* value(const ::novatel_msgs::CommonFooter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommonFooter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::novatel_msgs::CommonFooter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::novatel_msgs::CommonFooter_<ContainerAllocator>& v)
  {
    s << indent << "checksum: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOVATEL_MSGS_MESSAGE_COMMONFOOTER_H
