(cl:in-package novatel_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOLUTION_STATUS-VAL
          SOLUTION_STATUS
          POSITION_TYPE-VAL
          POSITION_TYPE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          UNDULATION-VAL
          UNDULATION
          DATUM_ID-VAL
          DATUM_ID
          LATITUDE_STD-VAL
          LATITUDE_STD
          LONGITUDE_STD-VAL
          LONGITUDE_STD
          ALTITUDE_STD-VAL
          ALTITUDE_STD
          STN_ID-VAL
          STN_ID
          DIFF_AGE-VAL
          DIFF_AGE
          SOL_AGE-VAL
          SOL_AGE
          SVS-VAL
          SVS
          SOL_SVS-VAL
          SOL_SVS
          L1_SVS-VAL
          L1_SVS
          MULT_SVS-VAL
          MULT_SVS
          RESERVED-VAL
          RESERVED
          EXTSOLSTAT-VAL
          EXTSOLSTAT
          GAL_SIG_MASK-VAL
          GAL_SIG_MASK
          SIG_MASK-VAL
          SIG_MASK
))