(cl:in-package novatel_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          WEEK-VAL
          WEEK
          GPSSEC-VAL
          GPSSEC
          POS11-VAL
          POS11
          POS12-VAL
          POS12
          POS13-VAL
          POS13
          POS21-VAL
          POS21
          POS22-VAL
          POS22
          POS23-VAL
          POS23
          POS31-VAL
          POS31
          POS32-VAL
          POS32
          POS33-VAL
          POS33
          ATT11-VAL
          ATT11
          ATT12-VAL
          ATT12
          ATT13-VAL
          ATT13
          ATT21-VAL
          ATT21
          ATT22-VAL
          ATT22
          ATT23-VAL
          ATT23
          ATT31-VAL
          ATT31
          ATT32-VAL
          ATT32
          ATT33-VAL
          ATT33
          VEL11-VAL
          VEL11
          VEL12-VAL
          VEL12
          VEL13-VAL
          VEL13
          VEL21-VAL
          VEL21
          VEL22-VAL
          VEL22
          VEL23-VAL
          VEL23
          VEL31-VAL
          VEL31
          VEL32-VAL
          VEL32
          VEL33-VAL
          VEL33
))